### ISSUE TITLE
GAT setup - conda setup issue

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/ansible-pulsar#18]
```
pulsar@gat-4:~$ /mnt/pulsar/venv/bin/pulsar-main -c /mnt/pulsar/config/ --ini_path /mnt/pulsar/config/server.ini
/mnt/pulsar/venv/lib/python3.8/site-packages/pulsar/util/pastescript/loadwsgi.py:125: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  return pkg_resources.EntryPoint.parse("x=" + s).load(False)
2020-12-18 15:45:36,160 INFO  [pulsar.core][MainThread] Starting the Pulsar without a toolbox to white-list.Ensure this application is protected by firewall or a configured private token.
2020-12-18 15:45:36,161 WARNI [galaxy.tool_util.deps][MainThread] Path 'dependencies' does not exist, ignoring
2020-12-18 15:45:36,161 WARNI [galaxy.tool_util.deps][MainThread] Path 'dependencies' is not directory, ignoring
2020-12-18 15:45:36,166 ERROR [pulsar.main][MainThread] Failed to initialize Pulsar application
Traceback (most recent call last):
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/pulsar/main.py", line 158, in _app
    pulsar_app = load_pulsar_app(
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/pulsar/main.py", line 132, in load_pulsar_app
    pulsar_app = pulsar.core.PulsarApp(**config)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/pulsar/core.py", line 52, in __init__
    self.__setup_dependency_manager(conf)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/pulsar/core.py", line 147, in __setup_dependency_manager
    self.dependency_manager = build_dependency_manager(app_config_dict=conf, default_tool_dependency_dir=default_tool_dependency_dir)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/__init__.py", line 90, in build_dependency_manager
    dependency_manager = DependencyManager(**dependency_manager_kwds)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/__init__.py", line 131, in __init__
    self.dependency_resolvers = self.__parse_resolver_conf_plugins(plugin_source)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/__init__.py", line 333, in __parse_resolver_conf_plugins
    return plugin_config.load_plugins(self.resolver_classes, plugin_source, extra_kwds, plugin_type_keys=['type', 'resolver_type'])
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/util/plugin_config.py", line 37, in load_plugins
    return __load_plugins_from_dicts(plugins_dict, plugin_source.source, extra_kwds, plugin_type_keys=plugin_type_keys)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/util/plugin_config.py", line 81, in __load_plugins_from_dicts
    plugin = plugins_dict[plugin_type](**plugin_kwds)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/resolvers/conda.py", line 137, in __init__
    self.disabled = not galaxy.tool_util.deps.installable.ensure_installed(conda_context, install_conda, self.auto_init)
  File "/mnt/pulsar/venv/lib/python3.8/site-packages/galaxy/tool_util/deps/installable.py", line 66, in ensure_installed
    os.mkdir(parent_path)
PermissionError: [Errno 13] Permission denied: '/mnt/pulsar/venv/lib/python3.8/site-packages/dependencies'
```

config is relatively straightforward

```
- hosts: pulsarservers
  roles:
    - galaxyproject.pulsar
```

and

```
galaxy_server_url: gat-0.training.galaxyproject.eu

pulsar_root: /mnt/pulsar

pulsar_pip_install: true
pulsar_pycurl_ssl_library: openssl
pulsar_systemd: true
pulsar_systemd_runner: webless

pulsar_create_user: true
pulsar_user: {name: pulsar, shell: /bin/bash}

pulsar_optional_dependencies:
  - pyOpenSSL
  # For remote transfers initiated on the Pulsar end rather than the Galaxy end
  - pycurl
  # drmaa required if connecting to an external DRM using it.
  - drmaa
  # kombu needed if using a message queue
  - kombu
  # psutil and pylockfile are optional dependencies but can make Pulsar
  # more robust in small ways.
  - psutil

pulsar_yaml_config:
  conda_auto_init: True
  conda_auto_install: True
  staging_directory: "{{ pulsar_staging_dir }}"
  persistence_directory: "{{ pulsar_persistence_dir }}"
  # The following are the settings for the pulsar server to contact the message queue with related timeouts etc.
  message_queue_url: "pyamqp://galaxy_au:{{ rabbitmq_password_galaxy_au }}@{{ galaxy_server_url }}:5671/pulsar/galaxu_au?ssl=1"
  min_polling_interval: 0.5
  amqp_publish_retry: True
  amqp_publish_retry_max_retries: 5
  amqp_publish_retry_interval_start: 10
  amqp_publish_retry_interval_step: 10
  amqp_publish_retry_interval_max: 60

pulsar_dependency_resolvers:
  - name: conda
    args:
      - name: auto_init
        value: true

```

ping @Slugger70  no idea why it's not using the dependency directory

**Comment by Slugger70** [comment]
No idea either..
I'll look into it

**Comment by hexylena** [comment]
> We just need to set tool_dependency_dir to `{{pulsar_root}}/deps` manually in the pulsar app.yml config
